import type { CatalogItem, PetSpecies, RoomBlueprint, RoomPlacement } from "@/lib/game/types";

export const petSpecies: PetSpecies[] = [
  {
    id: "cloud-fox",
    name: "Cloud Fox",
    temperament: "Gentle guardian",
    favoriteTreat: "Moonberry biscuit",
    colors: ["cream", "blush", "lavender"],
  },
  {
    id: "meadow-bunny",
    name: "Meadow Bunny",
    temperament: "Curious and bright",
    favoriteTreat: "Honey clover",
    colors: ["cream", "mint", "sky"],
  },
  {
    id: "tea-bear",
    name: "Tea Bear",
    temperament: "Sleepy helper",
    favoriteTreat: "Cinnamon stars",
    colors: ["honey", "cream", "blush"],
  },
  {
    id: "pond-duck",
    name: "Pond Duck",
    temperament: "Tiny optimist",
    favoriteTreat: "Garden peas",
    colors: ["honey", "sky", "mint"],
  },
];

export const starterCatalog: CatalogItem[] = [
  {
    id: "cozy-rug-blush",
    name: "Blush Hearth Rug",
    category: "flooring",
    description: "A soft oval rug that makes any room feel warmer.",
    priceCoins: 120,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "rug-blush",
    placementType: "floor",
    tags: ["room", "cozy", "starter"],
  },
  {
    id: "window-garden-arch",
    name: "Garden Arch Window",
    category: "wall",
    description: "A window with climbing leaves and a clear view of the meadow.",
    priceCoins: 180,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "window-arch",
    placementType: "wall",
    tags: ["room", "wall", "garden"],
  },
  {
    id: "lamp-honey-lantern",
    name: "Honey Lantern",
    category: "decor",
    description: "Warm light for late-night letters and quiet visits.",
    priceCoins: 95,
    priceHearts: 1,
    rarity: "starter",
    assetKey: "lantern-honey",
    placementType: "floor",
    tags: ["room", "garden", "light"],
  },
  {
    id: "chair-lavender-cushion",
    name: "Lavender Reading Chair",
    category: "furniture",
    description: "A small chair for your companion to nap beside.",
    priceCoins: 210,
    priceHearts: 0,
    rarity: "common",
    assetKey: "chair-lavender",
    placementType: "floor",
    tags: ["room", "seat"],
  },
  {
    id: "bed-cream-canopy",
    name: "Cream Canopy Bed",
    category: "furniture",
    description: "A soft tucked-in bed where your companion can curl up after garden watch.",
    priceCoins: 320,
    priceHearts: 2,
    rarity: "common",
    assetKey: "bed-cream",
    placementType: "floor",
    tags: ["room", "sleep"],
  },
  {
    id: "table-honey-tea",
    name: "Honey Tea Table",
    category: "furniture",
    description: "A tiny round table for moonberry tea and handwritten notes.",
    priceCoins: 165,
    priceHearts: 1,
    rarity: "common",
    assetKey: "table-honey",
    placementType: "floor",
    tags: ["room", "tea"],
  },
  {
    id: "shelf-memory-oak",
    name: "Memory Oak Shelf",
    category: "furniture",
    description: "A warm little shelf for keepsakes, shells, and saved letters.",
    priceCoins: 210,
    priceHearts: 1,
    rarity: "common",
    assetKey: "shelf-oak",
    placementType: "wall",
    tags: ["room", "memory"],
  },
  {
    id: "plant-sweetfern-pot",
    name: "Sweetfern Pot",
    category: "decor",
    description: "A leafy plant that sways whenever the room feels loved.",
    priceCoins: 105,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "plant-sweetfern",
    placementType: "floor",
    tags: ["room", "plant"],
  },
  {
    id: "planter-moonberry",
    name: "Moonberry Planter",
    category: "garden",
    description: "A starter planter that grows moonberries over time.",
    priceCoins: 150,
    priceHearts: 1,
    rarity: "starter",
    assetKey: "planter-moonberry",
    placementType: "garden_plot",
    tags: ["garden", "crop"],
  },
  {
    id: "note-paper-cream",
    name: "Cream Letter Set",
    category: "keepsake",
    description: "Stationery for private notes and memory book pages.",
    priceCoins: 60,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "letter-cream",
    placementType: "inventory_only",
    tags: ["notes", "memory"],
  },
  {
    id: "casper-moonberry-plush",
    name: "Casper Moonberry Plush",
    category: "decor",
    description: "A tiny Casper plush holding a moonberry for cozy public rooms.",
    priceCoins: 140,
    priceHearts: 1,
    rarity: "common",
    assetKey: "casper-moonberry-plush",
    placementType: "floor",
    tags: ["room", "casper", "cozy"],
  },
  {
    id: "sofa-blush-cloud",
    name: "Blush Cloud Sofa",
    category: "furniture",
    description: "A soft sofa for room parties, pet naps, and cozy visits.",
    priceCoins: 420,
    priceHearts: 3,
    rarity: "common",
    assetKey: "sofa-blush-cloud",
    placementType: "floor",
    tags: ["room", "seat", "party"],
  },
  {
    id: "fireplace-honey-stone",
    name: "Honey Stone Fireplace",
    category: "furniture",
    description: "Warm light, soft shadows, and a focal point for winter rooms.",
    priceCoins: 520,
    priceHearts: 4,
    rarity: "rare",
    assetKey: "fireplace-honey-stone",
    placementType: "wall",
    tags: ["room", "light", "cozy"],
  },
  {
    id: "piano-lavender-upright",
    name: "Lavender Upright Piano",
    category: "furniture",
    description: "A playable-looking piano for date nights, recitals, and party rooms.",
    priceCoins: 680,
    priceHearts: 5,
    rarity: "rare",
    assetKey: "piano-lavender-upright",
    placementType: "floor",
    tags: ["room", "music", "party"],
  },
  {
    id: "game-table-garden",
    name: "Garden Game Table",
    category: "furniture",
    description: "A small table for cards, board games, and multiplayer hangouts.",
    priceCoins: 380,
    priceHearts: 2,
    rarity: "common",
    assetKey: "game-table-garden",
    placementType: "floor",
    tags: ["room", "games", "party"],
  },
  {
    id: "pet-bed-moonberry",
    name: "Moonberry Pet Bed",
    category: "decor",
    description: "A tiny plush bed where Casper and other companions can sleep.",
    priceCoins: 220,
    priceHearts: 2,
    rarity: "common",
    assetKey: "pet-bed-moonberry",
    placementType: "floor",
    tags: ["pet", "sleep", "casper"],
  },
  {
    id: "wardrobe-keeper-oak",
    name: "Keeper Wardrobe",
    category: "furniture",
    description: "A wardrobe for future avatar outfits, colors, and cozy accessories.",
    priceCoins: 460,
    priceHearts: 3,
    rarity: "common",
    assetKey: "wardrobe-keeper-oak",
    placementType: "floor",
    tags: ["avatar", "customization", "room"],
  },
  {
    id: "fountain-lantern-patio",
    name: "Lantern Patio Fountain",
    category: "garden",
    description: "A sparkling fountain for outdoor rooms and shared gardens.",
    priceCoins: 560,
    priceHearts: 4,
    rarity: "rare",
    assetKey: "fountain-lantern-patio",
    placementType: "garden_plot",
    tags: ["garden", "water", "animated"],
  },
  {
    id: "dance-rug-party-star",
    name: "Starlit Party Rug",
    category: "flooring",
    description: "A glowing dance rug for parties, emotes, and group screenshots.",
    priceCoins: 340,
    priceHearts: 2,
    rarity: "common",
    assetKey: "dance-rug-party-star",
    placementType: "floor",
    tags: ["party", "room", "emotes"],
  },
  {
    id: "room-sunbeam-kitchen",
    name: "Sunbeam Kitchen Room",
    category: "room",
    description: "Unlock a bright kitchen room for baking, snacks, and companion care.",
    priceCoins: 900,
    priceHearts: 8,
    rarity: "common",
    assetKey: "room-sunbeam-kitchen",
    placementType: "inventory_only",
    tags: ["room-unlock", "kitchen"],
  },
  {
    id: "room-lavender-library",
    name: "Lavender Library Room",
    category: "room",
    description: "Unlock a quiet library for memory pages, reading corners, and soft piano music.",
    priceCoins: 1100,
    priceHearts: 10,
    rarity: "rare",
    assetKey: "room-lavender-library",
    placementType: "inventory_only",
    tags: ["room-unlock", "library"],
  },
  {
    id: "room-garden-patio",
    name: "Lantern Garden Patio",
    category: "room",
    description: "Unlock an outdoor 2.5D patio connected to gardens and friend visits.",
    priceCoins: 1250,
    priceHearts: 12,
    rarity: "rare",
    assetKey: "room-garden-patio",
    placementType: "inventory_only",
    tags: ["room-unlock", "garden", "party"],
  },
  {
    id: "room-cloud-observatory",
    name: "Cloud Observatory Room",
    category: "room",
    description: "Unlock a moonlit sky room for star watching, dates, and dreamy parties.",
    priceCoins: 1600,
    priceHearts: 16,
    rarity: "rare",
    assetKey: "room-cloud-observatory",
    placementType: "inventory_only",
    tags: ["room-unlock", "sky", "date"],
  },
];

export const roomBlueprints: RoomBlueprint[] = [
  {
    id: "moonlit-loft",
    name: "Moonlit Loft",
    description: "Starter 2.5D room with a wall plane, floor plane, furniture layering, Casper, and Realtime visits.",
    priceCoins: 0,
    priceHearts: 0,
    theme: "loft",
    capacity: 6,
    tags: ["starter", "decoratable", "multiplayer"],
    href: "/app/room?room=moonlit-loft",
  },
  {
    id: "sunbeam-kitchen",
    name: "Sunbeam Kitchen",
    description: "A warm cooking room for pet care loops, snacks, and future baking mini-games.",
    priceCoins: 900,
    priceHearts: 8,
    theme: "kitchen",
    capacity: 4,
    tags: ["unlockable", "pet-care"],
    href: "/app/room?room=sunbeam-kitchen",
  },
  {
    id: "lavender-library",
    name: "Lavender Library",
    description: "A quiet memory-book room with shelves, soft lights, and future reading interactions.",
    priceCoins: 1100,
    priceHearts: 10,
    theme: "library",
    capacity: 4,
    tags: ["unlockable", "memory"],
    href: "/app/room?room=lavender-library",
  },
  {
    id: "lantern-patio",
    name: "Lantern Garden Patio",
    description: "An outdoor hangout room linked to gardens, parties, and friend visits.",
    priceCoins: 1250,
    priceHearts: 12,
    theme: "patio",
    capacity: 8,
    tags: ["unlockable", "garden", "party"],
    href: "/app/room?room=lantern-patio",
  },
  {
    id: "cloud-observatory",
    name: "Cloud Observatory",
    description: "A premium moonlit room for dates, stargazing, and floating decor.",
    priceCoins: 1600,
    priceHearts: 16,
    theme: "observatory",
    capacity: 8,
    tags: ["unlockable", "date", "premium"],
    href: "/app/room?room=cloud-observatory",
  },
];

export const starterPlacements: RoomPlacement[] = [
  {
    id: "placement-rug",
    catalogItemId: "cozy-rug-blush",
    x: 360,
    y: 326,
    rotation: 0,
    scale: 1,
    zIndex: 1,
  },
  {
    id: "placement-window",
    catalogItemId: "window-garden-arch",
    x: 368,
    y: 128,
    rotation: 0,
    scale: 1,
    zIndex: 0,
  },
  {
    id: "placement-lantern",
    catalogItemId: "lamp-honey-lantern",
    x: 560,
    y: 260,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-chair",
    catalogItemId: "chair-lavender-cushion",
    x: 208,
    y: 280,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-bed",
    catalogItemId: "bed-cream-canopy",
    x: 594,
    y: 210,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-table",
    catalogItemId: "table-honey-tea",
    x: 432,
    y: 318,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-shelf",
    catalogItemId: "shelf-memory-oak",
    x: 214,
    y: 148,
    rotation: 0,
    scale: 1,
    zIndex: 0,
  },
  {
    id: "placement-plant",
    catalogItemId: "plant-sweetfern-pot",
    x: 642,
    y: 336,
    rotation: 0,
    scale: 1,
    zIndex: 3,
  },
];

export const privateGiftMilestones = [
  "Private Partner Garden",
  "Garden Guardian",
  "Message Milestone",
  "Study Week Quest",
  "Shared Visit Quest",
  "Milestone Quest",
];
