import type { CatalogItem, PetSpecies, RoomBlueprint, RoomPlacement } from "@/lib/game/types";

export const petSpecies: PetSpecies[] = [
  {
    id: "cloud-fox",
    name: "Cloud Fox",
    temperament: "Gentle guardian",
    favoriteTreat: "Moonberry biscuit",
    colors: ["cream", "blush", "lavender"],
  },
  {
    id: "moonberry-fox",
    name: "Moonberry Fox",
    temperament: "Playful stargazer",
    favoriteTreat: "Lavender moonberries",
    colors: ["cream", "mint", "sky"],
  },
  {
    id: "honey-fox",
    name: "Honey Fox",
    temperament: "Sleepy helper",
    favoriteTreat: "Cinnamon stars",
    colors: ["honey", "cream", "blush"],
  },
  {
    id: "garden-fox",
    name: "Garden Fox",
    temperament: "Tiny optimist",
    favoriteTreat: "Garden peas",
    colors: ["honey", "sky", "mint"],
  },
];

export const starterCatalog: CatalogItem[] = [
  {
    id: "cozy-rug-blush",
    name: "Blush Hearth Rug",
    category: "flooring",
    description: "A soft oval rug that makes any room feel warmer.",
    priceCoins: 120,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "rug-blush",
    placementType: "floor",
    tags: ["room", "cozy", "starter"],
  },
  {
    id: "window-garden-arch",
    name: "Garden Arch Window",
    category: "wall",
    description: "A window with climbing leaves and a clear view of the meadow.",
    priceCoins: 180,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "window-arch",
    placementType: "wall",
    tags: ["room", "wall", "garden"],
  },
  {
    id: "lamp-honey-lantern",
    name: "Honey Lantern",
    category: "decor",
    description: "Warm light for late-night letters and quiet visits.",
    priceCoins: 95,
    priceHearts: 1,
    rarity: "starter",
    assetKey: "lantern-honey",
    placementType: "floor",
    tags: ["room", "garden", "light"],
  },
  {
    id: "chair-lavender-cushion",
    name: "Lavender Reading Chair",
    category: "furniture",
    description: "A small chair for your companion to nap beside.",
    priceCoins: 210,
    priceHearts: 0,
    rarity: "common",
    assetKey: "chair-lavender",
    placementType: "floor",
    tags: ["room", "seat"],
  },
  {
    id: "bed-cream-canopy",
    name: "Cream Canopy Bed",
    category: "furniture",
    description: "A soft tucked-in bed where your companion can curl up after garden watch.",
    priceCoins: 320,
    priceHearts: 2,
    rarity: "common",
    assetKey: "bed-cream",
    placementType: "floor",
    tags: ["room", "sleep"],
  },
  {
    id: "table-honey-tea",
    name: "Honey Tea Table",
    category: "furniture",
    description: "A tiny round table for moonberry tea and handwritten notes.",
    priceCoins: 165,
    priceHearts: 1,
    rarity: "common",
    assetKey: "table-honey",
    placementType: "floor",
    tags: ["room", "tea"],
  },
  {
    id: "shelf-memory-oak",
    name: "Memory Oak Shelf",
    category: "furniture",
    description: "A warm little shelf for keepsakes, shells, and saved letters.",
    priceCoins: 210,
    priceHearts: 1,
    rarity: "common",
    assetKey: "shelf-oak",
    placementType: "wall",
    tags: ["room", "memory"],
  },
  {
    id: "plant-sweetfern-pot",
    name: "Sweetfern Pot",
    category: "decor",
    description: "A leafy plant that sways whenever the room feels loved.",
    priceCoins: 105,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "plant-sweetfern",
    placementType: "floor",
    tags: ["room", "plant"],
  },
  {
    id: "planter-moonberry",
    name: "Moonberry Planter",
    category: "garden",
    description: "A starter planter that grows moonberries over time.",
    priceCoins: 150,
    priceHearts: 1,
    rarity: "starter",
    assetKey: "planter-moonberry",
    placementType: "garden_plot",
    tags: ["garden", "crop"],
  },
  {
    id: "note-paper-cream",
    name: "Cream Letter Set",
    category: "keepsake",
    description: "Stationery for private notes and memory book pages.",
    priceCoins: 60,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "letter-cream",
    placementType: "inventory_only",
    tags: ["notes", "memory"],
  },
  {
    id: "casper-moonberry-plush",
    name: "Casper Moonberry Plush",
    category: "decor",
    description: "A tiny Casper plush holding a moonberry for cozy public rooms.",
    priceCoins: 140,
    priceHearts: 1,
    rarity: "common",
    assetKey: "casper-moonberry-plush",
    placementType: "floor",
    tags: ["room", "casper", "cozy"],
  },
  {
    id: "sofa-blush-cloud",
    name: "Blush Cloud Sofa",
    category: "furniture",
    description: "A soft sofa for room parties, pet naps, and cozy visits.",
    priceCoins: 420,
    priceHearts: 3,
    rarity: "common",
    assetKey: "sofa-blush-cloud",
    placementType: "floor",
    tags: ["room", "seat", "party"],
  },
  {
    id: "fireplace-honey-stone",
    name: "Honey Stone Fireplace",
    category: "furniture",
    description: "Warm light, soft shadows, and a focal point for winter rooms.",
    priceCoins: 520,
    priceHearts: 4,
    rarity: "rare",
    assetKey: "fireplace-honey-stone",
    placementType: "wall",
    tags: ["room", "light", "cozy"],
  },
  {
    id: "piano-lavender-upright",
    name: "Lavender Upright Piano",
    category: "furniture",
    description: "A playable-looking piano for date nights, recitals, and party rooms.",
    priceCoins: 680,
    priceHearts: 5,
    rarity: "rare",
    assetKey: "piano-lavender-upright",
    placementType: "floor",
    tags: ["room", "music", "party"],
  },
  {
    id: "game-table-garden",
    name: "Garden Game Table",
    category: "furniture",
    description: "A small table for cards, board games, and multiplayer hangouts.",
    priceCoins: 380,
    priceHearts: 2,
    rarity: "common",
    assetKey: "game-table-garden",
    placementType: "floor",
    tags: ["room", "games", "party"],
  },
  {
    id: "pet-bed-moonberry",
    name: "Moonberry Pet Bed",
    category: "decor",
    description: "A tiny plush bed where Casper and other companions can sleep.",
    priceCoins: 220,
    priceHearts: 2,
    rarity: "common",
    assetKey: "pet-bed-moonberry",
    placementType: "floor",
    tags: ["pet", "sleep", "casper"],
  },
  {
    id: "wardrobe-keeper-oak",
    name: "Keeper Wardrobe",
    category: "furniture",
    description: "A wardrobe for future avatar outfits, colors, and cozy accessories.",
    priceCoins: 460,
    priceHearts: 3,
    rarity: "common",
    assetKey: "wardrobe-keeper-oak",
    placementType: "floor",
    tags: ["avatar", "customization", "room"],
  },
  {
    id: "fountain-lantern-patio",
    name: "Lantern Patio Fountain",
    category: "garden",
    description: "A sparkling fountain for outdoor rooms and shared gardens.",
    priceCoins: 560,
    priceHearts: 4,
    rarity: "rare",
    assetKey: "fountain-lantern-patio",
    placementType: "garden_plot",
    tags: ["garden", "water", "animated"],
  },
  {
    id: "dance-rug-party-star",
    name: "Starlit Party Rug",
    category: "flooring",
    description: "A glowing dance rug for parties, emotes, and group screenshots.",
    priceCoins: 340,
    priceHearts: 2,
    rarity: "common",
    assetKey: "dance-rug-party-star",
    placementType: "floor",
    tags: ["party", "room", "emotes"],
  },
  {
    id: "room-sunbeam-kitchen",
    name: "Sunbeam Kitchen Room",
    category: "room",
    description: "Unlock a bright kitchen room for baking, snacks, and companion care.",
    priceCoins: 900,
    priceHearts: 8,
    rarity: "common",
    assetKey: "room-sunbeam-kitchen",
    placementType: "inventory_only",
    tags: ["room-unlock", "kitchen"],
  },
  {
    id: "room-lavender-library",
    name: "Lavender Library Room",
    category: "room",
    description: "Unlock a quiet library for memory pages, reading corners, and soft piano music.",
    priceCoins: 1100,
    priceHearts: 10,
    rarity: "rare",
    assetKey: "room-lavender-library",
    placementType: "inventory_only",
    tags: ["room-unlock", "library"],
  },
  {
    id: "room-garden-patio",
    name: "Lantern Garden Patio",
    category: "room",
    description: "Unlock an outdoor 2.5D patio connected to gardens and friend visits.",
    priceCoins: 1250,
    priceHearts: 12,
    rarity: "rare",
    assetKey: "room-garden-patio",
    placementType: "inventory_only",
    tags: ["room-unlock", "garden", "party"],
  },
  {
    id: "room-cloud-observatory",
    name: "Cloud Observatory Room",
    category: "room",
    description: "Unlock a moonlit sky room for star watching, dates, and dreamy parties.",
    priceCoins: 1600,
    priceHearts: 16,
    rarity: "rare",
    assetKey: "room-cloud-observatory",
    placementType: "inventory_only",
    tags: ["room-unlock", "sky", "date"],
  },
];

export const seasonalCatalog: CatalogItem[] = [
  {
    id: "pumpkin-porch-lantern",
    name: "Pumpkin Porch Lantern",
    category: "decor",
    description: "A carved pumpkin lantern with soft violet moonlight for Halloween rooms.",
    priceCoins: 240,
    priceHearts: 2,
    rarity: "rare",
    assetKey: "pumpkin-porch-lantern",
    placementType: "floor",
    tags: ["seasonal", "season:halloween", "room", "light"],
  },
  {
    id: "moonlight-bat-garland",
    name: "Moonlight Bat Garland",
    category: "wall",
    description: "Tiny paper bats strung across a wall with cozy lavender sparkle lights.",
    priceCoins: 180,
    priceHearts: 1,
    rarity: "common",
    assetKey: "moonlight-bat-garland",
    placementType: "wall",
    tags: ["seasonal", "season:halloween", "room", "wall"],
  },
  {
    id: "casper-boo-bed",
    name: "Casper Boo Bed",
    category: "decor",
    description: "A plush moonlit pet bed with a tiny ghost blanket for Casper-style companions.",
    priceCoins: 320,
    priceHearts: 3,
    rarity: "rare",
    assetKey: "casper-boo-bed",
    placementType: "floor",
    tags: ["seasonal", "season:halloween", "pet", "sleep", "casper"],
  },
  {
    id: "room-midnight-masquerade",
    name: "Midnight Masquerade Room",
    category: "room",
    description: "Unlock a moonlit Halloween party room with violet lights and pumpkin corners.",
    priceCoins: 1450,
    priceHearts: 12,
    rarity: "rare",
    assetKey: "room-midnight-masquerade",
    placementType: "inventory_only",
    tags: ["seasonal", "season:halloween", "room-unlock", "party"],
  },
  {
    id: "winter-wish-tree",
    name: "Winter Wish Tree",
    category: "decor",
    description: "A soft glowing holiday tree for notes, wishes, and shared room visits.",
    priceCoins: 380,
    priceHearts: 4,
    rarity: "rare",
    assetKey: "winter-wish-tree",
    placementType: "floor",
    tags: ["seasonal", "season:christmas", "room", "light", "memory"],
  },
  {
    id: "snowflake-window-garland",
    name: "Snowflake Window Garland",
    category: "wall",
    description: "A snowy window trim with warm garland lights and cream ribbon.",
    priceCoins: 220,
    priceHearts: 2,
    rarity: "common",
    assetKey: "snowflake-window-garland",
    placementType: "wall",
    tags: ["seasonal", "season:christmas", "room", "wall"],
  },
  {
    id: "peppermint-cocoa-table",
    name: "Peppermint Cocoa Table",
    category: "furniture",
    description: "A holiday table set for cocoa, cookies, and late-night garden breaks.",
    priceCoins: 330,
    priceHearts: 3,
    rarity: "common",
    assetKey: "peppermint-cocoa-table",
    placementType: "floor",
    tags: ["seasonal", "season:christmas", "room", "table"],
  },
  {
    id: "room-cozy-carol-lodge",
    name: "Cozy Carol Lodge Room",
    category: "room",
    description: "Unlock a winter lodge for snow visits, warm lights, and holiday room parties.",
    priceCoins: 1550,
    priceHearts: 14,
    rarity: "rare",
    assetKey: "room-cozy-carol-lodge",
    placementType: "inventory_only",
    tags: ["seasonal", "season:christmas", "room-unlock", "lodge"],
  },
  {
    id: "midnight-countdown-clock",
    name: "Midnight Countdown Clock",
    category: "wall",
    description: "A golden wall clock that makes every room feel ready for a countdown.",
    priceCoins: 260,
    priceHearts: 3,
    rarity: "rare",
    assetKey: "midnight-countdown-clock",
    placementType: "wall",
    tags: ["seasonal", "season:new-year", "room", "wall", "party"],
  },
  {
    id: "confetti-star-rug",
    name: "Confetti Star Rug",
    category: "flooring",
    description: "A soft star rug sprinkled with gold and lavender confetti.",
    priceCoins: 260,
    priceHearts: 2,
    rarity: "common",
    assetKey: "confetti-star-rug",
    placementType: "floor",
    tags: ["seasonal", "season:new-year", "room", "party"],
  },
  {
    id: "sparkling-toast-table",
    name: "Sparkling Toast Table",
    category: "furniture",
    description: "A party table for countdown photos, sparkling juice, and memory-book pages.",
    priceCoins: 360,
    priceHearts: 4,
    rarity: "rare",
    assetKey: "sparkling-toast-table",
    placementType: "floor",
    tags: ["seasonal", "season:new-year", "room", "party"],
  },
  {
    id: "room-sky-lantern-countdown",
    name: "Sky Lantern Countdown Room",
    category: "room",
    description: "Unlock a New Year observatory with floating lanterns and party stars.",
    priceCoins: 1700,
    priceHearts: 16,
    rarity: "rare",
    assetKey: "room-sky-lantern-countdown",
    placementType: "inventory_only",
    tags: ["seasonal", "season:new-year", "room-unlock", "observatory", "party"],
  },
  {
    id: "starlight-picnic-blanket",
    name: "Starlight Picnic Blanket",
    category: "flooring",
    description: "A blush and sky picnic blanket for summer rooms and party corners.",
    priceCoins: 230,
    priceHearts: 2,
    rarity: "common",
    assetKey: "starlight-picnic-blanket",
    placementType: "floor",
    tags: ["seasonal", "season:july-fourth", "room", "party"],
  },
  {
    id: "firework-lantern-arch",
    name: "Firework Lantern Arch",
    category: "garden",
    description: "A safe sparkler arch for garden entrances and friend visit photos.",
    priceCoins: 420,
    priceHearts: 4,
    rarity: "rare",
    assetKey: "firework-lantern-arch",
    placementType: "garden_plot",
    tags: ["seasonal", "season:july-fourth", "garden", "light"],
  },
  {
    id: "berry-sparkler-fountain",
    name: "Berry Sparkler Fountain",
    category: "garden",
    description: "A gentle berry fountain with soft firework glows for July garden nights.",
    priceCoins: 520,
    priceHearts: 5,
    rarity: "rare",
    assetKey: "berry-sparkler-fountain",
    placementType: "garden_plot",
    tags: ["seasonal", "season:july-fourth", "garden", "water"],
  },
  {
    id: "room-summer-firework-patio",
    name: "Summer Firework Patio Room",
    category: "room",
    description: "Unlock a summer patio room with starlight bunting and soft sky fireworks.",
    priceCoins: 1500,
    priceHearts: 13,
    rarity: "rare",
    assetKey: "room-summer-firework-patio",
    placementType: "inventory_only",
    tags: ["seasonal", "season:july-fourth", "room-unlock", "patio", "party"],
  },
];

export const marketCatalog = [...starterCatalog, ...seasonalCatalog];

export const roomBlueprints: RoomBlueprint[] = [
  {
    id: "moonlit-loft",
    name: "Moonlit Loft",
    description: "Starter 2.5D room with a wall plane, floor plane, furniture layering, Casper, and Realtime visits.",
    priceCoins: 0,
    priceHearts: 0,
    theme: "loft",
    capacity: 6,
    tags: ["starter", "decoratable", "multiplayer"],
    href: "/app/room?room=moonlit-loft",
  },
  {
    id: "sunbeam-kitchen",
    name: "Sunbeam Kitchen",
    description: "A warm cooking room for pet care loops, snacks, and future baking mini-games.",
    priceCoins: 900,
    priceHearts: 8,
    theme: "kitchen",
    capacity: 4,
    tags: ["unlockable", "pet-care"],
    href: "/app/room?room=sunbeam-kitchen",
  },
  {
    id: "rose-studio",
    name: "Rose Studio",
    description: "A blank blush room shell for portraits, date keepsakes, and soft furniture builds.",
    priceCoins: 700,
    priceHearts: 6,
    theme: "loft",
    capacity: 4,
    tags: ["unlockable", "blank", "date"],
    href: "/app/room?room=rose-studio",
  },
  {
    id: "pet-nursery",
    name: "Pet Nursery",
    description: "A blank companion-care room for beds, toys, treats, and future pet routines.",
    priceCoins: 850,
    priceHearts: 7,
    theme: "patio",
    capacity: 4,
    tags: ["unlockable", "blank", "pet-care"],
    href: "/app/room?room=pet-nursery",
  },
  {
    id: "lavender-library",
    name: "Lavender Library",
    description: "A quiet memory-book room with shelves, soft lights, and future reading interactions.",
    priceCoins: 1100,
    priceHearts: 10,
    theme: "library",
    capacity: 4,
    tags: ["unlockable", "memory"],
    href: "/app/room?room=lavender-library",
  },
  {
    id: "lantern-patio",
    name: "Lantern Garden Patio",
    description: "An outdoor hangout room linked to gardens, parties, and friend visits.",
    priceCoins: 1250,
    priceHearts: 12,
    theme: "patio",
    capacity: 8,
    tags: ["unlockable", "garden", "party"],
    href: "/app/room?room=lantern-patio",
  },
  {
    id: "park-road-gate",
    name: "Park Road Gate",
    description: "A blank transition room that opens toward Honeyheart Park, road parties, and friend visits.",
    priceCoins: 1400,
    priceHearts: 12,
    theme: "patio",
    capacity: 8,
    tags: ["unlockable", "blank", "park", "party"],
    href: "/app/room?room=park-road-gate",
  },
  {
    id: "cloud-observatory",
    name: "Cloud Observatory",
    description: "A premium moonlit room for dates, stargazing, and floating decor.",
    priceCoins: 1600,
    priceHearts: 16,
    theme: "observatory",
    capacity: 8,
    tags: ["unlockable", "date", "premium"],
    href: "/app/room?room=cloud-observatory",
  },
  {
    id: "midnight-masquerade",
    name: "Midnight Masquerade",
    description: "A Halloween party room with violet moonlight, pumpkin corners, and cozy costume visits.",
    priceCoins: 1450,
    priceHearts: 12,
    theme: "lodge",
    capacity: 8,
    tags: ["seasonal", "season:halloween", "party"],
    href: "/app/room?room=midnight-masquerade",
  },
  {
    id: "cozy-carol-lodge",
    name: "Cozy Carol Lodge",
    description: "A winter lodge for snow visits, warm lights, pet naps, and holiday room parties.",
    priceCoins: 1550,
    priceHearts: 14,
    theme: "lodge",
    capacity: 8,
    tags: ["seasonal", "season:christmas", "party"],
    href: "/app/room?room=cozy-carol-lodge",
  },
  {
    id: "sky-lantern-countdown",
    name: "Sky Lantern Countdown",
    description: "A New Year observatory with floating lanterns, confetti stars, and countdown photos.",
    priceCoins: 1700,
    priceHearts: 16,
    theme: "observatory",
    capacity: 8,
    tags: ["seasonal", "season:new-year", "party"],
    href: "/app/room?room=sky-lantern-countdown",
  },
  {
    id: "summer-firework-patio",
    name: "Summer Firework Patio",
    description: "A July patio room with starlight bunting, berry drinks, and soft sky fireworks.",
    priceCoins: 1500,
    priceHearts: 13,
    theme: "patio",
    capacity: 8,
    tags: ["seasonal", "season:july-fourth", "party"],
    href: "/app/room?room=summer-firework-patio",
  },
];

export const starterPlacements: RoomPlacement[] = [];

export const privateGiftMilestones = [
  "Private Partner Garden",
  "Garden Guardian",
  "Message Milestone",
  "Study Week Quest",
  "Shared Visit Quest",
  "Milestone Quest",
];
