import type { CatalogItem, PetSpecies, RoomPlacement } from "@/lib/game/types";

export const petSpecies: PetSpecies[] = [
  {
    id: "cloud-fox",
    name: "Cloud Fox",
    temperament: "Gentle guardian",
    favoriteTreat: "Moonberry biscuit",
    colors: ["cream", "blush", "lavender"],
  },
  {
    id: "meadow-bunny",
    name: "Meadow Bunny",
    temperament: "Curious and bright",
    favoriteTreat: "Honey clover",
    colors: ["cream", "mint", "sky"],
  },
  {
    id: "tea-bear",
    name: "Tea Bear",
    temperament: "Sleepy helper",
    favoriteTreat: "Cinnamon stars",
    colors: ["honey", "cream", "blush"],
  },
  {
    id: "pond-duck",
    name: "Pond Duck",
    temperament: "Tiny optimist",
    favoriteTreat: "Garden peas",
    colors: ["honey", "sky", "mint"],
  },
];

export const starterCatalog: CatalogItem[] = [
  {
    id: "cozy-rug-blush",
    name: "Blush Hearth Rug",
    category: "flooring",
    description: "A soft oval rug that makes any room feel warmer.",
    priceCoins: 120,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "rug-blush",
    placementType: "floor",
    tags: ["room", "cozy", "starter"],
  },
  {
    id: "window-garden-arch",
    name: "Garden Arch Window",
    category: "wall",
    description: "A window with climbing leaves and a clear view of the meadow.",
    priceCoins: 180,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "window-arch",
    placementType: "wall",
    tags: ["room", "wall", "garden"],
  },
  {
    id: "lamp-honey-lantern",
    name: "Honey Lantern",
    category: "decor",
    description: "Warm light for late-night letters and quiet visits.",
    priceCoins: 95,
    priceHearts: 1,
    rarity: "starter",
    assetKey: "lantern-honey",
    placementType: "floor",
    tags: ["room", "garden", "light"],
  },
  {
    id: "chair-lavender-cushion",
    name: "Lavender Reading Chair",
    category: "furniture",
    description: "A small chair for your companion to nap beside.",
    priceCoins: 210,
    priceHearts: 0,
    rarity: "common",
    assetKey: "chair-lavender",
    placementType: "floor",
    tags: ["room", "seat"],
  },
  {
    id: "bed-cream-canopy",
    name: "Cream Canopy Bed",
    category: "furniture",
    description: "A soft tucked-in bed where your companion can curl up after garden watch.",
    priceCoins: 320,
    priceHearts: 2,
    rarity: "common",
    assetKey: "bed-cream",
    placementType: "floor",
    tags: ["room", "sleep"],
  },
  {
    id: "table-honey-tea",
    name: "Honey Tea Table",
    category: "furniture",
    description: "A tiny round table for moonberry tea and handwritten notes.",
    priceCoins: 165,
    priceHearts: 1,
    rarity: "common",
    assetKey: "table-honey",
    placementType: "floor",
    tags: ["room", "tea"],
  },
  {
    id: "shelf-memory-oak",
    name: "Memory Oak Shelf",
    category: "furniture",
    description: "A warm little shelf for keepsakes, shells, and saved letters.",
    priceCoins: 210,
    priceHearts: 1,
    rarity: "common",
    assetKey: "shelf-oak",
    placementType: "wall",
    tags: ["room", "memory"],
  },
  {
    id: "plant-sweetfern-pot",
    name: "Sweetfern Pot",
    category: "decor",
    description: "A leafy plant that sways whenever the room feels loved.",
    priceCoins: 105,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "plant-sweetfern",
    placementType: "floor",
    tags: ["room", "plant"],
  },
  {
    id: "planter-moonberry",
    name: "Moonberry Planter",
    category: "garden",
    description: "A starter planter that grows moonberries over time.",
    priceCoins: 150,
    priceHearts: 1,
    rarity: "starter",
    assetKey: "planter-moonberry",
    placementType: "garden_plot",
    tags: ["garden", "crop"],
  },
  {
    id: "note-paper-cream",
    name: "Cream Letter Set",
    category: "keepsake",
    description: "Stationery for private notes and memory book pages.",
    priceCoins: 60,
    priceHearts: 0,
    rarity: "starter",
    assetKey: "letter-cream",
    placementType: "inventory_only",
    tags: ["notes", "memory"],
  },
];

export const starterPlacements: RoomPlacement[] = [
  {
    id: "placement-rug",
    catalogItemId: "cozy-rug-blush",
    x: 360,
    y: 326,
    rotation: 0,
    scale: 1,
    zIndex: 1,
  },
  {
    id: "placement-window",
    catalogItemId: "window-garden-arch",
    x: 368,
    y: 128,
    rotation: 0,
    scale: 1,
    zIndex: 0,
  },
  {
    id: "placement-lantern",
    catalogItemId: "lamp-honey-lantern",
    x: 560,
    y: 260,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-chair",
    catalogItemId: "chair-lavender-cushion",
    x: 208,
    y: 280,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-bed",
    catalogItemId: "bed-cream-canopy",
    x: 594,
    y: 210,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-table",
    catalogItemId: "table-honey-tea",
    x: 432,
    y: 318,
    rotation: 0,
    scale: 1,
    zIndex: 2,
  },
  {
    id: "placement-shelf",
    catalogItemId: "shelf-memory-oak",
    x: 214,
    y: 148,
    rotation: 0,
    scale: 1,
    zIndex: 0,
  },
  {
    id: "placement-plant",
    catalogItemId: "plant-sweetfern-pot",
    x: 642,
    y: 336,
    rotation: 0,
    scale: 1,
    zIndex: 3,
  },
];

export const privateGiftMilestones = [
  "Private Partner Garden",
  "Garden Guardian",
  "Message Milestone",
  "Study Week Quest",
  "Shared Visit Quest",
  "Milestone Quest",
];
