-- Seasonal holiday catalog items. The app filters these by date using the season tags and metadata windows.

insert into public.catalog_items
  (id, category, name, description, price_coins, price_hearts, rarity, asset_key, placement_type, tags, metadata)
values
  (
    'pumpkin-porch-lantern',
    'decor',
    'Pumpkin Porch Lantern',
    'A carved pumpkin lantern with soft violet moonlight for Halloween rooms.',
    240,
    2,
    'rare',
    'pumpkin-porch-lantern',
    'floor',
    array['seasonal', 'season:halloween', 'room', 'light'],
    '{"season": "halloween", "window": "10-01..11-02"}'::jsonb
  ),
  (
    'moonlight-bat-garland',
    'wall',
    'Moonlight Bat Garland',
    'Tiny paper bats strung across a wall with cozy lavender sparkle lights.',
    180,
    1,
    'common',
    'moonlight-bat-garland',
    'wall',
    array['seasonal', 'season:halloween', 'room', 'wall'],
    '{"season": "halloween", "window": "10-01..11-02"}'::jsonb
  ),
  (
    'casper-boo-bed',
    'decor',
    'Casper Boo Bed',
    'A plush moonlit pet bed with a tiny ghost blanket for Casper-style companions.',
    320,
    3,
    'rare',
    'casper-boo-bed',
    'floor',
    array['seasonal', 'season:halloween', 'pet', 'sleep', 'casper'],
    '{"season": "halloween", "window": "10-01..11-02"}'::jsonb
  ),
  (
    'room-midnight-masquerade',
    'room',
    'Midnight Masquerade Room',
    'Unlock a moonlit Halloween party room with violet lights and pumpkin corners.',
    1450,
    12,
    'rare',
    'room-midnight-masquerade',
    'inventory_only',
    array['seasonal', 'season:halloween', 'room-unlock', 'party'],
    '{"season": "halloween", "window": "10-01..11-02"}'::jsonb
  ),
  (
    'winter-wish-tree',
    'decor',
    'Winter Wish Tree',
    'A soft glowing holiday tree for notes, wishes, and shared room visits.',
    380,
    4,
    'rare',
    'winter-wish-tree',
    'floor',
    array['seasonal', 'season:christmas', 'room', 'light', 'memory'],
    '{"season": "christmas", "window": "12-01..12-26"}'::jsonb
  ),
  (
    'snowflake-window-garland',
    'wall',
    'Snowflake Window Garland',
    'A snowy window trim with warm garland lights and cream ribbon.',
    220,
    2,
    'common',
    'snowflake-window-garland',
    'wall',
    array['seasonal', 'season:christmas', 'room', 'wall'],
    '{"season": "christmas", "window": "12-01..12-26"}'::jsonb
  ),
  (
    'peppermint-cocoa-table',
    'furniture',
    'Peppermint Cocoa Table',
    'A holiday table set for cocoa, cookies, and late-night garden breaks.',
    330,
    3,
    'common',
    'peppermint-cocoa-table',
    'floor',
    array['seasonal', 'season:christmas', 'room', 'table'],
    '{"season": "christmas", "window": "12-01..12-26"}'::jsonb
  ),
  (
    'room-cozy-carol-lodge',
    'room',
    'Cozy Carol Lodge Room',
    'Unlock a winter lodge for snow visits, warm lights, and holiday room parties.',
    1550,
    14,
    'rare',
    'room-cozy-carol-lodge',
    'inventory_only',
    array['seasonal', 'season:christmas', 'room-unlock', 'lodge'],
    '{"season": "christmas", "window": "12-01..12-26"}'::jsonb
  ),
  (
    'midnight-countdown-clock',
    'wall',
    'Midnight Countdown Clock',
    'A golden wall clock that makes every room feel ready for a countdown.',
    260,
    3,
    'rare',
    'midnight-countdown-clock',
    'wall',
    array['seasonal', 'season:new-year', 'room', 'wall', 'party'],
    '{"season": "new-year", "window": "12-27..01-07"}'::jsonb
  ),
  (
    'confetti-star-rug',
    'flooring',
    'Confetti Star Rug',
    'A soft star rug sprinkled with gold and lavender confetti.',
    260,
    2,
    'common',
    'confetti-star-rug',
    'floor',
    array['seasonal', 'season:new-year', 'room', 'party'],
    '{"season": "new-year", "window": "12-27..01-07"}'::jsonb
  ),
  (
    'sparkling-toast-table',
    'furniture',
    'Sparkling Toast Table',
    'A party table for countdown photos, sparkling juice, and memory-book pages.',
    360,
    4,
    'rare',
    'sparkling-toast-table',
    'floor',
    array['seasonal', 'season:new-year', 'room', 'party'],
    '{"season": "new-year", "window": "12-27..01-07"}'::jsonb
  ),
  (
    'room-sky-lantern-countdown',
    'room',
    'Sky Lantern Countdown Room',
    'Unlock a New Year observatory with floating lanterns and party stars.',
    1700,
    16,
    'rare',
    'room-sky-lantern-countdown',
    'inventory_only',
    array['seasonal', 'season:new-year', 'room-unlock', 'observatory', 'party'],
    '{"season": "new-year", "window": "12-27..01-07"}'::jsonb
  ),
  (
    'starlight-picnic-blanket',
    'flooring',
    'Starlight Picnic Blanket',
    'A blush and sky picnic blanket for summer rooms and party corners.',
    230,
    2,
    'common',
    'starlight-picnic-blanket',
    'floor',
    array['seasonal', 'season:july-fourth', 'room', 'party'],
    '{"season": "july-fourth", "window": "07-01..07-07"}'::jsonb
  ),
  (
    'firework-lantern-arch',
    'garden',
    'Firework Lantern Arch',
    'A safe sparkler arch for garden entrances and friend visit photos.',
    420,
    4,
    'rare',
    'firework-lantern-arch',
    'garden_plot',
    array['seasonal', 'season:july-fourth', 'garden', 'light'],
    '{"season": "july-fourth", "window": "07-01..07-07"}'::jsonb
  ),
  (
    'berry-sparkler-fountain',
    'garden',
    'Berry Sparkler Fountain',
    'A gentle berry fountain with soft firework glows for July garden nights.',
    520,
    5,
    'rare',
    'berry-sparkler-fountain',
    'garden_plot',
    array['seasonal', 'season:july-fourth', 'garden', 'water'],
    '{"season": "july-fourth", "window": "07-01..07-07"}'::jsonb
  ),
  (
    'room-summer-firework-patio',
    'room',
    'Summer Firework Patio Room',
    'Unlock a summer patio room with starlight bunting and soft sky fireworks.',
    1500,
    13,
    'rare',
    'room-summer-firework-patio',
    'inventory_only',
    array['seasonal', 'season:july-fourth', 'room-unlock', 'patio', 'party'],
    '{"season": "july-fourth", "window": "07-01..07-07"}'::jsonb
  )
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  price_coins = excluded.price_coins,
  price_hearts = excluded.price_hearts,
  rarity = excluded.rarity,
  asset_key = excluded.asset_key,
  placement_type = excluded.placement_type,
  tags = excluded.tags,
  metadata = excluded.metadata,
  active = true,
  updated_at = now();
